### ISSUE TITLE
Error when I use params = TestNet3Params.get();

### ISSUE THREAD

**Issue by alexanderjca** [bitcoin-dot-org/bitcoin.org#2400]
When I run the following code:
       NetworkParameters params;
        String filePrefix;
    	filePrefix = "MyWalletBTC";
        
    	BriefLogFormatter.init();
    	params = TestNet3Params.get();

       kit = new WalletAppKit(params, new File("c:\\WorkSpace\\laboratorio"), filePrefix) {
       ........

I got an error:
Exception in thread "main" Exception in thread " STARTING" java.lang.IllegalStateException: Expected the service to be RUNNING, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:285)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:229)
	at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:151)
	at app3.ejempplo3.App.main(App.java:82)
Caused by: org.bitcoinj.wallet.UnreadableWalletException$WrongNetwork: Mismatched network ID
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:464)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:440)
	at org.bitcoinj.kits.WalletAppKit.loadWallet(WalletAppKit.java:402)
	at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:364)
	at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:273)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Unknown Source)
java.lang.RuntimeException: org.bitcoinj.wallet.UnreadableWalletException$WrongNetwork: Mismatched network ID
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:58)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bitcoinj.wallet.UnreadableWalletException$WrongNetwork: Mismatched network ID
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:464)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:440)
	at org.bitcoinj.kits.WalletAppKit.loadWallet(WalletAppKit.java:402)
	at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:364)
	at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:273)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	... 2 more 

I don't know What's the problem; please someone could me help??

**Comment by alexanderjca** [comment]
By the way when I use:
params = MainNetParams.get();

the code runs and it creates an bitcoin address

**Comment by wbnns** [comment]
@alexanderjca Hello, it looks like you're working with [bitcoinj](https://github.com/bitcoinj/bitcoinj). This repository is for issues and changes directly related to the Bitcoin.org codebase.

Have you tried opening your issue on the bitcoinj repository? They may have better insight.
